### ISSUE TITLE
Docs not available

### ISSUE THREAD

**Issue by schlaus** [stacktracejs/stacktrace.js#131]
The docs (http://www.stacktracejs.com/docs/stacktrace-js) are not currently accessible. Console says http://www.stacktracejs.com/docs/index.build.js is giving 404.

**Comment by eriwen** [comment]
The website switched to `#!` for navigation due to Google crawl errors. Docs are available at [http://www.stacktracejs.com/#!/docs/stacktrace-js](http://www.stacktracejs.com/#!/docs/stacktrace-js)

Could you please tell us what linked to http://www.stacktracejs.com/docs/stacktrace-js so we can correct it?

**Comment by schlaus** [comment]
Ah, sorry for withholding that. As far as I can tell all the links at the main site http://www.stacktracejs.com point to the incorrect url.

**Comment by schlaus** [comment]
And in addition it seems opening internal links in the docs to a new tab or copying a link's url also results in a version without the hashbang.

**Comment by eriwen** [comment]
All should be good now. Please let us know if you see any other problems. Thank you!
