### ISSUE TITLE
Is there any open source dashboard to display errors?

### ISSUE THREAD

**Issue by rayqian** [stacktracejs/stacktrace.js#145]

**Comment by eriwen** [comment]
Not that I'm aware of, but I'd hope this tool would make something like that easier.

**Comment by rayqian** [comment]
@eriwen what's difference between stacktrace.js and https://github.com/csnover/TraceKit ?

My purpose is to gather client side errors, then send them to the server.

Stacktrace.js has more functions, but i'm not sure i need that.

**Comment by eriwen** [comment]
My general understanding of the intent of Tracekit is to hook into as many native/jquery error handlers as possible and propagate through a pub/sub API. The internals of the 2 projects are fairly similar.

I'd encourage you to look at both seriously and choose the one you're most comfortable putting in production. It sounds like both may fulfill your need. I'm happy to answer any questions about stacktrace.js to help you decide

**Comment by eriwen** [comment]
@rayqian I want to note that stacktrace.js uses [stack-generator](https://github.com/stacktracejs/stack-generator) internally to support old browsers. 

We were made aware of an IE-specific bug in Error parsing awhile ago, but that has been resolved. Also note that ehe usage of error-stack-parser has [risen sharply](https://www.npmjs.com/package/error-stack-parser) since its debut a couple months ago.

**Comment by eriwen** [comment]
This issue isn't directly related to this project. Please email me (address on my profile) for any further discussion.
