### ISSUE TITLE
getting anonymous instead of function names.

### ISSUE THREAD

**Issue by kfirufk** [stacktracejs/stacktrace.js#169]
Hi! this library looks interesting. I'm trying to fetch current stack trace with function names, lines of code and even with used parameters to functions.

it seems like I do get a small trace that shows a lot of functions with their parameters but it shows 'anonymous' instead, and it doesn't show the file and line that this was function was found in. 

I'm using angular 1 in my client project in case it's relevant.

I'm testing this library on a Gentoo Linux 64 bit, the server is NodeJS v6.2.2 and I'm using many other javascript libraries.

angularjs{route,animate,aria}: 1.5.7
angular-bootstrap: 1.3.3
angular-material: 1.0.9
stackframe: 1.0.2
stack-generator: 1.1.0
stacktrace-js: 1.3.0

I tried many methods to create and show current stack trace. this is my final version:

```
       var st = StackGenerator.backtrace();
       var sf = new StackFrame();
       sf.setArgs(st);
       console.info(sf.toString());
```

one more thing. in the documentation at https://www.stacktracejs.com/#!/docs/stacktrace-js about getting a stack trace from the current location, I had to delete the last two lines of the example, for it to run without errors.

which means that this:

StackTrace.get().then(callback).catch(errback)
=> Promise(Array[StackFrame], Error)
=> callback([StackFrame('func1', [], 'file.js', 203, 9), StackFrame('func2', [], 'http://localhost:3000/file.min.js', 1, 3284)])

what changed to this:

StackTrace.get().then(callback).catch(errback);

and this actually provides the same output as my code above. 
I'm probably missing something. can you assist me please ? :)

**Comment by eriwen** [comment]
I'm sorry that the documentation has failed you here.Most users do want to use `StackTrace.get().then(callback).catch(errback);` as you said.

In order to figure out why you're getting `'anonymous'` for all of your function names, it'd be helpful if you could provide a sample of the output from stacktrace.js. Even better would be using `try { throw new Error(); } catch(e) { console.log(e.stack) }` _instead_ of where you call `StackTrace.get().then....` and paste what you get.

**Comment by eriwen** [comment]
This hasn't had a response on months, so closing as dormant.
