### ISSUE TITLE
Error in Parse url domain

### ISSUE THREAD

**Issue by giansalex** [stacktracejs/stacktrace.js#206]
I have domain with dashes, but url result have only first domain word
MySite: https://aspnetbundle-prod.us-east-1.elasticbeanstalk.com/

![image](https://user-images.githubusercontent.com/14926587/39832611-4612c148-538d-11e8-9a48-ed55aa897837.png)

## Expected Behavior
https://aspnetbundle-prod.us-east-1.elasticbeanstalk.com/Scripts/app.js

## Current Behavior
https://aspnetbundle/Scripts/app.js

## Steps to Reproduce (for bugs)
Use domain with dashes

## Your Environment
* stacktrace.js version: 2.0.0
* Browser Name and version: Chrome 64.0.3282.186 (Build oficial)
* Operating System and version:  Windows 10 Pro  (64 bits)
* Link to your project: https://github.com/giansalex/aspnet-bundling-sourcemap

## Possible Solution
change Regex to : 
```js
var urlRegexp = /^(?:([\w+\-.]+):)?\/\/(?:(\w+:\w+)@)?([\w.\-]*)(?::(\d+))?(\S*)$/
```
https://github.com/stacktracejs/stacktrace.js/blob/master/dist/stacktrace.js#L1857

**Comment by bradleyhamm** [comment]
Thanks for your report--I have the same issue. This URL parse issue appears to have been fixed in source-map@0.6.0: https://github.com/mozilla/source-map/commit/215590b9d09da7f72bf9763a074e6c0ccc0dfe1a#diff-efe561bdbff5cb09f13b5648ff47c376R740

A potential workaround may be to update an npm-shrinkwrap.json with source-map@0.6.1.
