### ISSUE TITLE
Support for source maps?

### ISSUE THREAD

**Issue by TimeForAChange** [stacktracejs/stacktrace.js#44]
It would be nice to have support for source maps, because stack traces for minified concatenated files are quite useless. This would seem a most excellent enhancement :)

http://www.html5rocks.com/en/tutorials/developertools/sourcemaps/
http://www.sitepoint.com/what-are-source-maps-all-about/

This github project may have it: https://github.com/janekp/mapstrace

The minifier yuglify version 2 seems to have support for source map creation, as does the Closure compiler.

http://code.google.com/p/closure-compiler/wiki/SourceMaps

**Comment by mbrgm** [comment]
Really looking forward to this!

**Comment by eriwen** [comment]
@mbrgm You can test it out with what's on master. Your feedback would be greatly appreciated. Please submit any issues to stacktracejs/stacktrace-gps

**Comment by niemyjski** [comment]
+1

**Comment by mbrgm** [comment]
@eriwen I tried it, but maybe it's not working because I'm using webpack.

I put together [a quick example](https://github.com/mbrgm/stacktrace-js-sourcemaps-example.git). If you look at [`src/scripts/index.js#9-12`](https://github.com/mbrgm/stacktrace-js-sourcemaps-example/blob/master/src/scripts/index.js#L9-12), that's were I'd like to print the stacktrace of the caught ReferenceError, which is created when requiring `app.js`.

I would really appreciate if you could have a look at the example and maybe tell me what I'd have to change. You can run a test server from within the repo directory using `./node_modules/.bin/webpack-dev-server --inline -d --hot`. Thank you!

**Comment by eriwen** [comment]
@mbrgm Thanks for the thorough example. I'll get to this asap (probably before end of weekend).

**Comment by eriwen** [comment]
@mbrgm I got your example working by simply changing your `package.json` to point to `stacktrace.js/dist/stacktrace.min.js` which includes all dependencies.

I ran `./node_modules/.bin/webpack` and served up the build directory and got 7-entry Stack Trace. Is that what you wanted?

**Comment by mbrgm** [comment]
@eriwen Could you maybe fork and push your working version? I'm able to get a stacktrace as well, but all of the entries point to the created bundle.js; the webpack-generated sourcemaps don't seem to be considered for resolving.

**Comment by eriwen** [comment]
@mbrgm Ah, yes I misunderstood you. 

That said, I've made some progress and I believe I've found a case where stacktrace-gps is failing too fast (it tries to GET the webpack:/// url from the source map and the browser throws an access denied error). 

This has been *very* valuable. I'm going to get this fixed, then send you a pull request to your example repo as soon as I can!

**Comment by yoav-zibin** [comment]
BTW, if anyone is looking for a one-time way to decode an exception (instead of planting client -side code to do it), you can use this:
http://yoav-zibin.github.io/emulator/decode_stacktrace/decode.html

I copied the script in 
https://github.com/novocaine/sourcemapped-stacktrace/
and modified it a bit to handle Mozilla stacktraces (that have a slightly different format).

If you get CORS errors (i.e., no Access-Control-Allow-Origin header) in the console, then you can use my AppEngine as a proxy by using:  decode.html?yoavfetchurl

        // Mozilla: 
        // Stack: k@http://ajax.googleapis.com/ajax/libs/angularjs/1.3.8/angular.min.js:118:287
        // Chrome: 
        // at http://ajax.googleapis.com/ajax/libs/angularjs/1.3.8/angular.min.js:112:276
        // at l.$eval (http://ajax.googleapis.com/ajax/libs/angularjs/1.3.8/angular.min.js:126:83)

**Comment by niemyjski** [comment]
any updates on this?

**Comment by oliversalzburg** [comment]
Seems like the initial request is being taken care of by https://github.com/stacktracejs/stacktrace-gps Any outstanding issues with that project should be reported over there.
